name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DJ_CA_CI_MODE: "true"
  PGHOST: localhost
  PGUSER: postgres
  PGPASSWORD: postgres

jobs:
  unittest-python:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        env:
          POSTGRES_DB: django_ca
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      fail-fast: false
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install cli tools
        run: |
          python -m pip install --upgrade pipx
          python -m pipx ensurepath
          pipx install phosphorus yamk
      - name: Create the virtual environment
        run: |
          python -m venv .venv
          echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV
          echo "$PWD/.venv/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          yam install_py -g main -g test
      - name: Run migrations
        run: |
          yam migrations
      - name: Test the project
        run: |
          yam -e tests
